config/routes.rb
Rails.application.routes.draw do
  resources :ideas

  root 'ideas#new'

end

app/models/idea.rb
class Idea < ActiveRecord::Base

  validates_length_of :ipn, is: 7, message: "Hey, IPN tem 7 caractéres"
  validates_presence_of :name, message: "Não vai dizer qual sua Sugestão?"


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  http_basic_authenticate_with name: "equipeinova", password: "senha123", except: [:new, :show, :create]
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Já recebemos sua Ideia, boa sorte.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:ipn, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :ipn, :class => "col-sm-2 control-label"%>
    <div class="col-sm-2">
      <%= f.text_field :ipn, :class => "form-control"  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label"%>
    <div class="col-sm-6">
      <%= f.text_field :name, :class => "form-control" %>
    </div> 
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit value: "Salvar Ideia", :class => "btn btn-primary btn-large" %>
    </div>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Ipn</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.ipn %></td>
        <td><%= idea.name %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<%= render 'form' %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>IPN:</strong>
  <%= @idea.ipn %>
</p>

<p>
  <strong>Sugestão:</strong>
  <%= @idea.name %>
</p>

<%= link_to 'Mais uma Sugestão?', root_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Concurso Cultural</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'jumbotron-narrow', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'ie10-viewport-bug-workaround', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'ie10-viewport-bug-workaround', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'ie-emulation-modes-warning', 'data-turbolinks-track' => true %>
	  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 0px;">

    <div class="container">
      <div class="header clearfix" style="padding: 0px;">
        <!-- <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" class="active"><a href="#">Home</a></li>
            <li role="presentation"><a href="#">About</a></li>
            <li role="presentation"><a href="#">Contact</a></li>
          </ul>
        </nav> -->

         <nav>
          <ul class="nav nav-pills col-centered">
            <h3 class="text-muted"><%= image_tag 'Groupe Renault.png', class: "logo" %></h3>
          </ul>
        </nav>
        
      </div>

      <div class="jumbotron">
        <h1>Concurso Cultural<br>Evento Inovação</h1>
        <p class="lead" style="text-align: left;font-size: 18px;">
          Com objetivo de promover a <strong>Transformação Digital</strong> na <strong>Renault</strong> e gerar <strong>oportunidades de novos negócios e eficiência,</strong> 
          a <strong>DSIA</strong> realizará em setembro um evento onde fornecedores renomados de tecnologia estarão no <strong>Complexo Ayrton Senna</strong> 
          apresentando o que há de mais recente em <strong>inovação de TI para indústria automotiva</strong>.  
          
 <br>
<br>
Um evento como este não pode ficar sem um nome forte e impactante, não acha?<br>Então, coloque em prática seu lado criativo, crie um nome original e cadastre aqui até o dia <strong>20/05 (sexta-feira).</strong>
<br>
<br>
O autor da melhor ideia ganhará um *voucher para uma confraternização.<br> <strong>Participe e boa sorte!</strong></p>

	<p style="font-size: 14px;text-align: right;padding-top: 24px;">*Limite de R$ 300,00.</p>
        
      </div>

      <div class="row marketing">
        <%= yield %>        
      </div>

      <footer class="footer">
        <p>© 2016 Renault do Brasil, Inc.</p>
      </footer>

    </div> <!-- /container -->


</body>
</html>